image: gitpod/workspace-mysql
tasks:
  - init: |
      sudo service mysql start
      mysql -u root -e "CREATE DATABASE IF NOT EXISTS job_board"
      cp .env.example .env
      composer install
      php artisan key:generate
  - command: php artisan migrate --seed && php artisan serve --host=0.0.0.0 --port=8000
ports:
  - port: 8000
    onOpen: open-preview
